[workspace]
members = [
    "circuits-storage-common",
    "pallets/mobile-registry",
    "pallets/ocw-circuits",
    "pallets/ocw-garble",
    "pallets/tx-registry",
    "pallets/tx-validation",
]
resolver = "2"

# https://docs.rust-embedded.org/embedonomicon/smallest-no-std.html?search=global_allocator
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[workspace.dependencies]
log = { version = "0.4", default-features = false }

# Prepare for https://github.com/integritee-network/pallets/blob/3cd57250f694e7dc931d48686eacac8505481c87/Cargo.toml#L28
# but for now using the versions from https://github.com/integritee-network/pallets/blob/b07c044856aca63b5e07a401da676fffaadae48a/primitives/claims/Cargo.toml#L16
frame-benchmarking = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42" }
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42" }
parity-scale-codec = { version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.0.1", default-features = false, features = ["derive"] }
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42" }
sp-io = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42" }
sp-keystore = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42" }

################################################################################
# [patch."https://github.com/Interstellar-Network/lib-garble-rs.git"]
# lib-garble-rs = { path = "../lib-garble-rs/lib-garble-rs/" }

# [patch."https://github.com/Interstellar-Network/rs-common.git"]
# interstellar-http-client = { path = "../rs-common/http-client/" }
# tests-utils = { path = "../rs-common/tests_utils/" }
# interstellar-ipfs-client = { path = "../rs-common/ipfs-client-http-req/" }

# [patch."https://github.com/Interstellar-Network/lib_circuits.git"]
# circuit-gen-rs = { path = "../lib_circuits/circuit-gen-rs" }
# circuit-types-rs = { path = "../lib_circuits/circuit-types-rs" }
################################################################################
